### ISSUE TITLE
Use current branch instead of fixed branch

### ISSUE THREAD

**Issue by ChristophTobler** [fabiospampinato/vscode-open-in-github#1]
Is it somehow possible to use the current branch instead of a fixed one? ->
`"openInGitHub.remote.branch": "master", // Name of the remote branch`

Maybe only use the specified branch if the current doesn't exist on Github.

**Comment by ChristophTobler** [comment]
Just saw it in the README... Sorry

**Comment by fabiospampinato** [comment]
Reading this issues I was thinking "yeah, that's how it should work, why didn't I code it this way?", glad to hear that I actually did 😄
