### ISSUE TITLE
Inverse operation: open in vscode from github

### ISSUE THREAD

**Issue by danielweck** [fabiospampinato/vscode-open-in-github#16]
Hello, great extension, thank you!
Very useful for code peer reviews over Slack / instant messaging, to exchange URLs whilst working locally from VSCode.
However the inverse functionality would be very useful too.

For example I would like to be able to copy such URL: `https://github.com/fabiospampinato/vscode-open-in-github/blob/92aebc8183323697c29f36baf8b6a78dd360525b/src/extension.ts#L8-L11`

https://github.com/fabiospampinato/vscode-open-in-github/blob/92aebc8183323697c29f36baf8b6a78dd360525b/src/extension.ts#L8-L11

...and to show `src/extension.ts` in VSCode with the code selection line 8-11 (extracted from the URL `#L8-L11`).

Any thoughts?

**Comment by fabiospampinato** [comment]
Sounds useful, perhaps that should be a separate extension, maybe that should be a browser extension.

**Comment by fabiospampinato** [comment]
I personally use https://github1s.com/ for stuff like that. That's out of scope with extension at this point in time.
