### ISSUE TITLE
Remote repository not found due to hardcoded filter

### ISSUE THREAD

**Issue by ReagentX** [fabiospampinato/vscode-open-in-github#17]
Using a custom installation of Github does not work because there is a hard-coded filter that excludes custom domains:

https://github.com/fabiospampinato/vscode-open-in-github/blob/92aebc8183323697c29f36baf8b6a78dd360525b/src/utils.ts#L106

Removing this string filter for `github.com` makes the filter work. This should not be a hardcoded string and instead a reference to the setting `openInGitHub.github.domain`.

**Comment by fabiospampinato** [comment]
PR welcome to add exactly that setting.

**Comment by fabiospampinato** [comment]
fixed in v1.2.4.
