### ISSUE TITLE
A shortcut button in Status Bar

### ISSUE THREAD

**Issue by antfu** [fabiospampinato/vscode-open-in-github#23]
Thanks for making this extension! This is exactly what I was looking for!

In addition to that, I think it would be nice to have an icon button in the status bar to navigate quickly.

The implement should be simple like this: 

https://github.com/antfu/vscode-open-in-github-button/blob/8d6c3791a3ae4ccf350ea4dc702d153f1bb7c21d/src/index.ts#L4-L8

If you like it, I am happy to send PR. Otherwise, I also built a tiny extension on top it to provide that button that you can try: https://github.com/antfu/vscode-open-in-github-button

Thank you

**Comment by vikiboss** [comment]
I made a [simple extension](https://github.com/vikiboss/vscode-open-in-github) to implement this feature, hoping it was helpful as a temporary alternative. ❤️

**Comment by fabiospampinato** [comment]
Thank you but for scenarios where it's not obvious that everybody would want a statusbar button, or what statusbar button to add, I think it's better to just use [`vscode-commands`](https://github.com/fabiospampinato/vscode-commands).

The problems are:
- I don't really want a button for this.
- It's unclear which button(s) should be added, do we want to open the project? the file? the file with a permalink?
- It conflicts with [other externsions](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-github-notifications-bell) that just must provide a button to the statusbar with that same icon.
