### ISSUE TITLE
feature: create a permalink for a line where cursor's at

### ISSUE THREAD

**Issue by cyberthirst** [fabiospampinato/vscode-open-in-github#27]
Hey, thanks for the extension. I have a feature request.

It would be really useful if we could add two commands for working with permalinks for specific lines within the files.

I very often want to share a specific line via a permalink - these commands would make so ez.

1st command: copy a permalink to the line where the cursor's currently at to the clipboard
2nd command: open the permalink to the line where the cursor's currently in the browser

**Comment by cyberthirst** [comment]
Another idea - use multiline cursors to do permalinks for line sequences, eg from loc11-loc20.

**Comment by fabiospampinato** [comment]
Is this not already implemented? If you set `openInGitHub.useLocalLine` to `true` you will get a line-aware permalink, either to open or to copy, depending on the command, and if you have a selection and `openInGitHub.useLocalRange` set to `true`, which is the default, the produced URL will be range-aware also.

**Comment by cyberthirst** [comment]
> Is this not already implemented? If you set `openInGitHub.useLocalLine` to `true` you will get a line-aware permalink, either to open or to copy, depending on the command, and if you have a selection and `openInGitHub.useLocalRange` set to `true`, which is the default, the produced URL will be range-aware also.

Ohh, my bad. Was only reading through the docs for commands, didn't realize they can be extended via config.
But yeah, it works perfectly and exactly as I wish it would. Thanks for making the extension!
