### ISSUE TITLE
Error: You have to open a git project before being able to open it in GitHub

### ISSUE THREAD

**Issue by anishmittal2020** [fabiospampinato/vscode-open-in-github#3]
I am working in a workspace which contains a set of folder. `.git` folder is in the parent folder not part of the workspace. When I try to open file in github using extension, I get this error: `You have to open a git project before being able to open it in GitHub`

What should I do?

**Comment by fabiospampinato** [comment]
The `.git` directory is expected to be inside the workspace. You should open that parent folder in VSC.

**Comment by kdeggelman** [comment]
@fabiospampinato thanks for your work on this project!

Would it make sense to recursively search in parent directories for the `.git` directory? My use case is that we have a large repository with many projects within the repository. It's nice for my workspace to be focused on a single project at a time.

I'd be happy to submit a pull request if you think this is a good idea.

**Comment by fabiospampinato** [comment]
@kdeggelman I don't remember why I added this limitation 🤔 your use case makes sense to me, PR welcome 👍 You'd basically just have to remove this line I think:

https://github.com/fabiospampinato/vscode-open-in-github/blob/472cc82a33634bd5720d8fa08e3b3aae9d4e3ff1/src/utils.ts#L63

**Comment by faximan** [comment]
I'm seeing this even with the root folder open in vscode. I can even see the `.git` folder in the left sidebar. Let me know how to debug this further.
