### ISSUE TITLE
feature request - open in GitHub based on repository defined in package.json

### ISSUE THREAD

**Issue by coliff** [fabiospampinato/vscode-open-in-github#4]
it'd be great if you didn't need to add new config settings for this to work and instead if there was a package.json in the project it'd use the 'repository field (if present).

**Comment by fabiospampinato** [comment]
You don't _need_ to specify any settings, they are totally optional.

Relying on a `package.json` file, or adding extra logic for it seems unnecessary, the extension works with the actual git repository and doesn't care what kind of project you are developing.

**Comment by coliff** [comment]
Ah yes, I didn't realise. Cool! Great extension - leaving a 5-star review now....
