### ISSUE TITLE
open project goes to   /undefined/undefined

### ISSUE THREAD

**Issue by mesqueeb** [fabiospampinato/vscode-open-in-github#5]
Ever since about three days, I cannot use:

> 'Open in GitHub: Project' // Open the current project in GitHub

It used to just open the project URL, but now it always opens the correct project URL but with an additional `/undefined/undefined` in the URI.

eg. if my project is `https://github.com/mesqueeb/is-what` it will open `https://github.com/mesqueeb/is-what/undefined/undefined`

This is my most used command so would highly appreciate any advice!!

**Comment by fabiospampinato** [comment]
@mesqueeb I'm sorry to hear that, I must have made a mistake in the latest update, fix coming soon!

**Comment by mesqueeb** [comment]
Thanks so much. I can’t live without this plugin! I use it like 10 times a day lol. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fabiospampinato** [comment]
Fixed in v1.1.5, thanks for reporting the issue!
