### ISSUE TITLE
Problem on windows

### ISSUE THREAD

**Issue by mesqueeb** [fabiospampinato/vscode-open-in-github#7]
Hi,

I have just suggested your extension to a friend who uses a windows. (🙄)

But he has a problem when he does **Github: open file**

The path that's opened has `%5C` in it. Which I believe is the windows reverse `/` equivalent of macOs `/` which is converted to `%2F` on macOS...

Github.com doesn't recognise `%5C` as a `/` and therefore shows a 404 error.

Can your  **Github: open file** make sure to convert `\` to `/` inside the urls that are opened?

Thanks so much!

**Comment by fabiospampinato** [comment]
@mesqueeb Could you paste an example broken url that this extension opens?

**Comment by tdk0718** [comment]
Hi,
I paste the URL which Mesqueeb said on upper below.
https://github.com/mesqueeb/sokketsu-helpers/blob/master/src%5Cadd.js

**Comment by fabiospampinato** [comment]
It looks like forward slashes need to need normalized under Windows, PR welcome 👍

**Comment by mesqueeb** [comment]
@fabiospampinato I can try but can you point me to an example how to normalize and where I should add that to the source to make a PR? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fabiospampinato** [comment]
@mesqueeb The filepath is being computed [here](https://github.com/fabiospampinato/vscode-open-in-github/blob/472cc82a33634bd5720d8fa08e3b3aae9d4e3ff1/src/commands.ts#L75). For normalizing it maybe you could just run something like: `.replace ( /\//g, '/' )` on it 🤔

**Comment by fabiospampinato** [comment]
The extension throws an error for me under a Windows VM, unfortunately I don't have the time to debug that right now.

**Comment by fabiospampinato** [comment]
@kdeggelman's PR should have fixed this 👍

**Comment by mesqueeb** [comment]
@tdk0718 can you check? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@fabiospampinato 
Hi Fabio,
I checked in with my friend, and the feature now works on Windows.
Thanks so much!

**Comment by fabiospampinato** [comment]
Awesome, thanks for letting me know.
