### ISSUE TITLE
Broken when using Remote - SSH

### ISSUE THREAD

**Issue by jeebay** [fabiospampinato/vscode-open-in-github#8]
The new [remote capabilities](https://code.visualstudio.com/blogs/2019/05/02/remote-development) introduced in the Insiders version of vscode allow opening projects hosted in containers and remote machines. When using this extension in the Insiders version on a remote repo the `Open in Github: File` command no longer works. 

It would be great if I could the browser on my local machine corresponding to the remote file that I am working on. 

Please let me know if there's any additional information I can provide.

**Comment by fabiospampinato** [comment]
> the Open in Github: File command no longer works.

Do the others work? 

If they don't I guess this will be fixed by using `vscode.openExternal` instead of the `open` module, PR welcome 👍

**Comment by jeebay** [comment]
I tested [this extension](https://github.com/d4rkr00t/vscode-open-in-github) and it works. Prefer yours because it requires one fewer click to actually open the file :).

**Comment by SeanTAllen** [comment]
@fabiospampinato none of the commands I've tested work.

**Comment by yelvert** [comment]
https://code.visualstudio.com/docs/remote/troubleshooting#_browser-does-not-open-locally

**Comment by tobiaskohlbau** [comment]
@yelvert thanks for posting the link. I've put together a PR would be keen if @fabiospampinato is willing to accept it.
